baseURL = 'https://kwanlung.github.io/'
languageCode = 'en-us'
title = 'DeanHub | Code Is Life'
theme = "PaperMod"
enableEmoji = true

mainSections = ["posts", "project"]

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  showArchive = true

  [params.profileMode]
    enabled = true
    title = "Dean Ng Kwan Lung"
    subtitle = " Dean's Code | Explore | Learn "
    imageUrl = "images/deanicontransparent.jpeg" # Place your profile image in 'static/images/'
    imageTitle = "Profile Image"
    imageWidth = 120
    imageHeight = 120

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/kwanlung"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/deanng00/"

  [params.assets]
  favicon = "favicon.ico"
  favicon32x32 = "favicon-32x32.png"
  apple_touch_icon = "apple-touch-icon.png"
  theme_color = "#1a1a1a"
  msapplication_TileColor = "#1a1a1a"


[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "project"
    name = "Projects"
    url = "/project/"
    weight = 3

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    identifier = "archive"
    name = "Archive"
    url = "/archives/"
    weight = 5